<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-01-01">

<title>ADS EBD - IPDMA prediction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="R prediction ipdma - practical_files/libs/clipboard/clipboard.min.js"></script>
<script src="R prediction ipdma - practical_files/libs/quarto-html/quarto.js"></script>
<script src="R prediction ipdma - practical_files/libs/quarto-html/popper.min.js"></script>
<script src="R prediction ipdma - practical_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="R prediction ipdma - practical_files/libs/quarto-html/anchor.min.js"></script>
<link href="R prediction ipdma - practical_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="R prediction ipdma - practical_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="R prediction ipdma - practical_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="R prediction ipdma - practical_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="R prediction ipdma - practical_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#preparation" id="toc-preparation" class="nav-link active" data-scroll-target="#preparation">Preparation</a></li>
  <li><a href="#chapter-1" id="toc-chapter-1" class="nav-link" data-scroll-target="#chapter-1">Chapter 1</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#general-aim" id="toc-general-aim" class="nav-link" data-scroll-target="#general-aim">1.1 General aim</a></li>
  <li><a href="#initialization" id="toc-initialization" class="nav-link" data-scroll-target="#initialization">1.2 Initialization</a></li>
  <li><a href="#exercise-data" id="toc-exercise-data" class="nav-link" data-scroll-target="#exercise-data">1.3 Exercise data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#chapter-2" id="toc-chapter-2" class="nav-link" data-scroll-target="#chapter-2">Chapter 2</a>
  <ul class="collapse">
  <li><a href="#univariable-associations" id="toc-univariable-associations" class="nav-link" data-scroll-target="#univariable-associations">Univariable associations</a></li>
  </ul></li>
  <li><a href="#chapter-3" id="toc-chapter-3" class="nav-link" data-scroll-target="#chapter-3">Chapter 3</a>
  <ul class="collapse">
  <li><a href="#multivariable-associations" id="toc-multivariable-associations" class="nav-link" data-scroll-target="#multivariable-associations">Multivariable associations</a>
  <ul class="collapse">
  <li><a href="#predictor-selection-using-lasso-on-the-overall-dataset-ignoring-clustering" id="toc-predictor-selection-using-lasso-on-the-overall-dataset-ignoring-clustering" class="nav-link" data-scroll-target="#predictor-selection-using-lasso-on-the-overall-dataset-ignoring-clustering">3.1 predictor selection using LASSO on the overall dataset (ignoring clustering)</a></li>
  </ul></li>
  <li><a href="#predictor-selection-using-lasso-with-mixed-effects" id="toc-predictor-selection-using-lasso-with-mixed-effects" class="nav-link" data-scroll-target="#predictor-selection-using-lasso-with-mixed-effects">3.2 predictor selection using LASSO with mixed effects</a></li>
  </ul></li>
  <li><a href="#chapter-4" id="toc-chapter-4" class="nav-link" data-scroll-target="#chapter-4">Chapter 4</a>
  <ul class="collapse">
  <li><a href="#internal-external-cross-validation-iecv" id="toc-internal-external-cross-validation-iecv" class="nav-link" data-scroll-target="#internal-external-cross-validation-iecv">Internal-external cross-validation (IECV)</a></li>
  </ul></li>
  <li><a href="#chapter-5" id="toc-chapter-5" class="nav-link" data-scroll-target="#chapter-5">Chapter 5</a>
  <ul class="collapse">
  <li><a href="#synthesis-of-performance-results" id="toc-synthesis-of-performance-results" class="nav-link" data-scroll-target="#synthesis-of-performance-results">Synthesis of performance results</a>
  <ul class="collapse">
  <li><a href="#visual-assessment" id="toc-visual-assessment" class="nav-link" data-scroll-target="#visual-assessment">5.1 Visual assessment</a></li>
  </ul></li>
  <li><a href="#meta-analysis-of-model-performance" id="toc-meta-analysis-of-model-performance" class="nav-link" data-scroll-target="#meta-analysis-of-model-performance">5.2 Meta-analysis of model performance</a>
  <ul class="collapse">
  <li><a href="#calibration-in-the-large" id="toc-calibration-in-the-large" class="nav-link" data-scroll-target="#calibration-in-the-large">5.2.1 Calibration-in-the-large</a></li>
  <li><a href="#total-oe-ratio" id="toc-total-oe-ratio" class="nav-link" data-scroll-target="#total-oe-ratio">5.2.2 Total O:E ratio</a></li>
  <li><a href="#calibration-slope" id="toc-calibration-slope" class="nav-link" data-scroll-target="#calibration-slope">5.2.3 Calibration slope</a></li>
  <li><a href="#concordance-statistic" id="toc-concordance-statistic" class="nav-link" data-scroll-target="#concordance-statistic">5.2.4 Concordance statistic</a></li>
  <li><a href="#overview-of-performance-estiamtes" id="toc-overview-of-performance-estiamtes" class="nav-link" data-scroll-target="#overview-of-performance-estiamtes">5.2.5 Overview of performance estiamtes</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#chapter-6" id="toc-chapter-6" class="nav-link" data-scroll-target="#chapter-6">Chapter 6</a>
  <ul class="collapse">
  <li><a href="#meta-regression" id="toc-meta-regression" class="nav-link" data-scroll-target="#meta-regression">Meta-regression</a></li>
  <li><a href="#calibration-in-the-large-1" id="toc-calibration-in-the-large-1" class="nav-link" data-scroll-target="#calibration-in-the-large-1">6.1 Calibration-in-the-large</a></li>
  <li><a href="#calibration-slope-1" id="toc-calibration-slope-1" class="nav-link" data-scroll-target="#calibration-slope-1">6.2 Calibration slope</a></li>
  </ul></li>
  <li><a href="#chapter-7" id="toc-chapter-7" class="nav-link" data-scroll-target="#chapter-7">Chapter 7</a>
  <ul class="collapse">
  <li><a href="#accounting-for-level-of-care" id="toc-accounting-for-level-of-care" class="nav-link" data-scroll-target="#accounting-for-level-of-care">Accounting for level of care</a></li>
  </ul></li>
  <li><a href="#chapter-8" id="toc-chapter-8" class="nav-link" data-scroll-target="#chapter-8">Chapter 8</a>
  <ul class="collapse">
  <li><a href="#comparison-of-models" id="toc-comparison-of-models" class="nav-link" data-scroll-target="#comparison-of-models">Comparison of models</a></li>
  </ul></li>
  <li><a href="#chapter-9" id="toc-chapter-9" class="nav-link" data-scroll-target="#chapter-9">Chapter 9</a>
  <ul class="collapse">
  <li><a href="#develop-final-model-to-be-reported" id="toc-develop-final-model-to-be-reported" class="nav-link" data-scroll-target="#develop-final-model-to-be-reported">Develop final model to be reported</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ADS EBD - IPDMA prediction</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Valentijn de Jong and Thomas Debray </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="preparation" class="level1">
<h1>Preparation</h1>
<p>This practical was developed using R version 4.2.2. Open RStudio and verify if your installed version is up-to-date:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">R.Version</span>()<span class="sc">$</span>version.string</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you are unfamiliar with R, an introduction tutorial is available <a href="http://r-tutorial.nl/">here</a>.</p>
</section>
<section id="chapter-1" class="level1">
<h1>Chapter 1</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Deep venous thrombosis (DVT) is a blood clot that forms in a vein in the body (usually in the lower leg or thigh). A (part of such) clot can break off and be carried through the bloodstream to the lungs and cause a blockage (pulmonary embolism), preventing oxygenation of the blood and potentially causing death. Clinical DVT diagnosis is not straightforward. For this reason, multivariable diagnostic prediction models have been developed during the past decades.</p>
<p>In this practical, you will use Individual Participant Data (IPD) sets from 9 studies that recruited consecutive outpatients with suspected deep vein thrombosis <span class="citation" data-cites="geersing_exclusion_2014">(<a href="#ref-geersing_exclusion_2014" role="doc-biblioref">Geersing et al. 2014</a>)</span>. These studies were identified by a systematic review and were required to have performed D-dimer testing before reference testing; and to document the presence or absence of proximal deep vein thrombosis by an acceptable reference test. Acceptable such tests were either compression ultrasonography or venography at initial presentation, or, if venous imaging was not performed, an uneventful follow-up for at least three months. More information on the included datasets can be found in <span class="citation" data-cites="geersing_exclusion_2014">Geersing et al. (<a href="#ref-geersing_exclusion_2014" role="doc-biblioref">2014</a>)</span>.</p>
<section id="general-aim" class="level3">
<h3 class="anchored" data-anchor-id="general-aim">1.1 General aim</h3>
<p>During this practical you will practice with developing and validating a model to predict the presence of DVT using IPD originating from 9 studies.</p>
</section>
<section id="initialization" class="level3">
<h3 class="anchored" data-anchor-id="initialization">1.2 Initialization</h3>
<p>Open R and install the packages needed to perform this practical</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"MASS"</span>, <span class="st">"Hmisc"</span>, <span class="st">"rms"</span>, <span class="st">"data.table"</span>, <span class="st">"glmmLasso"</span>, <span class="st">"metafor"</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"metamisc"</span>, <span class="st">"mnormt"</span>, <span class="st">"pROC"</span>, <span class="st">"car"</span>,<span class="st">"mvmeta"</span>, <span class="st">"glmnet"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Afterwards, we can load the necessary packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mnormt)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mvmeta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-data" class="level3">
<h3 class="anchored" data-anchor-id="exercise-data">1.3 Exercise data</h3>
<p>Download the practicum dataset <em>dvt_ipd.Rdata</em> and load the dataset <code>ipd</code> by opening the file:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">choose.dir</span>(<span class="fu">getwd</span>(), <span class="st">"Choose a suitable folder to store output of this practical"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">file.choose</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<p>Let’s first explore the characteristics of the 9 different studies:</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 21%">
<col style="width: 6%">
<col style="width: 14%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: right;">Year</th>
<th style="text-align: left;">Country</th>
<th style="text-align: right;">N</th>
<th style="text-align: left;">Prevalence</th>
<th style="text-align: left;">Reference</th>
<th style="text-align: left;">Line of Care</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">amuse</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">The Netherlands</td>
<td style="text-align: right;">1028</td>
<td style="text-align: left;">13 %</td>
<td style="text-align: left;">CUS</td>
<td style="text-align: left;">primary</td>
</tr>
<tr class="even">
<td style="text-align: left;">aida</td>
<td style="text-align: right;">2003</td>
<td style="text-align: left;">The Netherlands</td>
<td style="text-align: right;">814</td>
<td style="text-align: left;">39 %</td>
<td style="text-align: left;">CUS</td>
<td style="text-align: left;">secondary</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edit</td>
<td style="text-align: right;">2000</td>
<td style="text-align: left;">Canada</td>
<td style="text-align: right;">153</td>
<td style="text-align: left;">17 %</td>
<td style="text-align: left;">CUS or venography</td>
<td style="text-align: left;">secondary</td>
</tr>
<tr class="even">
<td style="text-align: left;">kraay</td>
<td style="text-align: right;">2002</td>
<td style="text-align: left;">The Netherlands</td>
<td style="text-align: right;">1756</td>
<td style="text-align: left;">23 %</td>
<td style="text-align: left;">CUS</td>
<td style="text-align: left;">secondary</td>
</tr>
<tr class="odd">
<td style="text-align: left;">toll</td>
<td style="text-align: right;">2006</td>
<td style="text-align: left;">The Netherlands</td>
<td style="text-align: right;">791</td>
<td style="text-align: left;">16 %</td>
<td style="text-align: left;">CUS</td>
<td style="text-align: left;">primary</td>
</tr>
<tr class="even">
<td style="text-align: left;">edited</td>
<td style="text-align: right;">2002</td>
<td style="text-align: left;">Canada</td>
<td style="text-align: right;">1075</td>
<td style="text-align: left;">18 %</td>
<td style="text-align: left;">CUS or venography</td>
<td style="text-align: left;">secondary</td>
</tr>
<tr class="odd">
<td style="text-align: left;">diem</td>
<td style="text-align: right;">2003</td>
<td style="text-align: left;">Canada</td>
<td style="text-align: right;">541</td>
<td style="text-align: left;">22 %</td>
<td style="text-align: left;">CUS</td>
<td style="text-align: left;">secondary</td>
</tr>
<tr class="even">
<td style="text-align: left;">stevens</td>
<td style="text-align: right;">2004</td>
<td style="text-align: left;">United States</td>
<td style="text-align: right;">436</td>
<td style="text-align: left;">14 %</td>
<td style="text-align: left;">CUS</td>
<td style="text-align: left;">secondary</td>
</tr>
<tr class="odd">
<td style="text-align: left;">oudega</td>
<td style="text-align: right;">2005</td>
<td style="text-align: left;">The Netherlands</td>
<td style="text-align: right;">1295</td>
<td style="text-align: left;">22 %</td>
<td style="text-align: left;">CUS</td>
<td style="text-align: left;">primary</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>CUS = compression ultrasonography</p>
<p><strong>Question 1.</strong> Do you observe any differences between studies conducted in primary and secondary care settings?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ipd);<span class="fu">dim</span>(ipd)  <span class="co"># show first six rows and dimensions of dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">length</span>(<span class="fu">table</span>(ipd<span class="sc">$</span>studyname))) <span class="co"># determine number of studies</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.table</span>(ipd[,<span class="sc">-</span><span class="dv">1</span>])[, <span class="fu">lapply</span>(.SD, mean), by <span class="ot">=</span> studyname] <span class="co"># summarize data per study</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data.table</span>(ipd[,<span class="sc">-</span><span class="dv">1</span>])[, <span class="fu">lapply</span>(.SD, sum), by <span class="ot">=</span> studyname]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An overview of the variables is given below:<br>
* <strong>studyid</strong>&nbsp;&nbsp;&nbsp;&nbsp;study identifier<br>
* <strong>care</strong>&nbsp;&nbsp;&nbsp;&nbsp;care level (primary (=1) / secondary (=0))<br>
* <strong>country</strong>&nbsp;&nbsp;&nbsp;&nbsp;country of study (Netherlands (=1) / Canada (=2) / Sweden (=3) / United States of America (=4))<br>
* <strong>sex</strong>&nbsp;&nbsp;&nbsp;&nbsp;sex of participants (male (=1) / female (=0))<br>
* <strong>age</strong>&nbsp;&nbsp;&nbsp;&nbsp;age (years)<br>
* <strong>side</strong>&nbsp;&nbsp;&nbsp;&nbsp;Side of legpain (left side (=0) / right side (=1) / both sides (=2))<br>
* <strong>durat</strong>&nbsp;&nbsp;&nbsp;&nbsp;duration of symptoms<br>
* <strong>malign</strong>&nbsp;&nbsp;&nbsp;&nbsp;active malignancy<br>
* <strong>par</strong>&nbsp;&nbsp;&nbsp;&nbsp;paresis<br>
* <strong>surg</strong>&nbsp;&nbsp;&nbsp;&nbsp;recent surgery (or bedridden)<br>
* <strong>tend</strong>&nbsp;&nbsp;&nbsp;&nbsp;tenderness venous system<br>
* <strong>leg</strong>&nbsp;&nbsp;&nbsp;&nbsp;entire leg swollen<br>
* <strong>calfdif</strong>&nbsp;&nbsp;&nbsp;&nbsp;calf difference<br>
* <strong>calfdif3</strong>&nbsp;&nbsp;&nbsp;&nbsp;calf difference &gt;= 3 cm<br>
* <strong>pit</strong>&nbsp;&nbsp;&nbsp;&nbsp;pitting edema<br>
* <strong>vein</strong>&nbsp;&nbsp;&nbsp;&nbsp;vein distension<br>
* <strong>altdiagn</strong>&nbsp;&nbsp;&nbsp;&nbsp;alternative diagnosis present<br>
* <strong>oachst</strong>&nbsp;&nbsp;&nbsp;&nbsp;oral contraceptives or hst<br>
* <strong>notraum</strong>&nbsp;&nbsp;&nbsp;&nbsp;absence of leg trauma<br>
* <strong>eryt</strong>&nbsp;&nbsp;&nbsp;&nbsp;erythema<br>
* <strong>histdvt</strong>&nbsp;&nbsp;&nbsp;&nbsp;history of previous DVT<br>
* <strong>histpe</strong>&nbsp;&nbsp;&nbsp;&nbsp;history of previous PE<br>
* <strong>coag</strong>&nbsp;&nbsp;&nbsp;&nbsp;family history of thrombofilia<br>
* <strong>trav</strong>&nbsp;&nbsp;&nbsp;&nbsp;prolonged travelling<br>
* <strong>pregn</strong>&nbsp;&nbsp;&nbsp;&nbsp;pregnancy<br>
* <strong>ddim</strong>&nbsp;&nbsp;&nbsp;&nbsp;d-dimer value<br>
* <strong>ddimdich</strong>&nbsp;&nbsp;&nbsp;&nbsp;dichotimized d-dimer value<br>
* <strong>typdim</strong>&nbsp;&nbsp;&nbsp;&nbsp;type of d-dimer assay used (qualitative assay (SimpliRED or Clearview Simplify D-dimer) (=1) / quantitative assay (Latex or Elisa D-dimer) (=2))<br>
* <strong>dvt</strong>&nbsp;&nbsp;&nbsp;&nbsp;final diagnosis of DVT<br>
* <strong>studyname</strong>&nbsp;&nbsp;&nbsp;&nbsp;study names</p>
<p><em>Answer: Side of leg pain seems to be mostly left in secondary care, while in primary care it is all over the place. Tenderness of the venous system, pitting edema, histdvt seem to be more prevalent in secondary care. No clear differences are seen for the other characteristics.</em></p>
<p><strong>Question 2.</strong> Which characteristics would you consider to be relevant for predicting presence of DVT in patients with suspected DVT?</p>
<p><em>Answer: In the published prediction models on DVT the following predictors are included: malign, par, surg, tend, leg, cdif3, pit, vein, altdiagn, histdvt, oachst, sex, notraum, ddimd.</em></p>
</section>
</section>
</section>
<section id="chapter-2" class="level1">
<h1>Chapter 2</h1>
<section id="univariable-associations" class="level2">
<h2 class="anchored" data-anchor-id="univariable-associations">Univariable associations</h2>
<p>Determine the univariable predictor effects of the included variables within each study.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dat.sel <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd,<span class="at">select=</span><span class="sc">-</span><span class="fu">c</span>(studyname,studyid,care,country,dvt,typdim))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>       </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># define a matrix to store coefficients</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>uni.coef <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">data =</span> <span class="cn">NA</span>, <span class="at">nrow =</span> n, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ncol =</span> <span class="fu">ncol</span>(dat.sel),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(uni.coef) <span class="ot">&lt;-</span> <span class="fu">names</span>(dat.sel)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(uni.coef) <span class="ot">&lt;-</span> <span class="fu">unique</span>(ipd<span class="sc">$</span>studyname)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># select data from study i out of n</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  ipd.uni <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd, ipd<span class="sc">$</span>studyid<span class="sc">==</span>i)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine the association between predictor j and dvt in study i</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(dat.sel)){</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    dat.uni <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd.uni, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(studyname,studyid,care,country,dvt,typdim))</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    ipd.uni<span class="sc">$</span>x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(dat.uni[j])</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    fit.uni <span class="ot">&lt;-</span> <span class="fu">glm</span>(dvt <span class="sc">~</span> x, <span class="at">data =</span> ipd.uni, <span class="at">family =</span> binomial)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    uni.coef[i,j] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">coef</span>(fit.uni)[<span class="dv">2</span>], <span class="at">digits=</span><span class="dv">4</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>uni.coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Question 3.</strong> Which predictors appear to be highly informative (i.e.&nbsp;strong associations)? Are there any predictor effects that substantially vary across studies?</p>
<p><em>Answer: Ddimdich and calfdif3 seem to be highly informative. There are several predictors for which we see contradictory effects (positive and negative associations) across studies, including sex, age, side, durat, par, tend, vein, oachst, notraum, histdvt, histpe, coag, trav, and pregn.</em></p>
</section>
</section>
<section id="chapter-3" class="level1">
<h1>Chapter 3</h1>
<section id="multivariable-associations" class="level2">
<h2 class="anchored" data-anchor-id="multivariable-associations">Multivariable associations</h2>
<p>Define predictors of interest (here: chosen arbitrarily, feel free to chose whichever predictors you prefer, based on clinical reasoning, literature and/or univariable associations) NOTE: the number of predictors may be problematic for some studies</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>explanatory <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"age"</span>,<span class="st">"par"</span>,<span class="st">"tend"</span>,<span class="st">"leg"</span>,<span class="st">"pit"</span>,<span class="st">"altdiagn"</span>,<span class="st">"histdvt"</span>,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"malign"</span>,<span class="st">"surg"</span>,<span class="st">"calfdif3"</span>,<span class="st">"vein"</span>,<span class="st">"oachst"</span>,<span class="st">"sex"</span>,<span class="st">"notraum"</span>,<span class="st">"ddimdich"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Alternatively, you could use statistical selection procedures.</p>
<section id="predictor-selection-using-lasso-on-the-overall-dataset-ignoring-clustering" class="level3">
<h3 class="anchored" data-anchor-id="predictor-selection-using-lasso-on-the-overall-dataset-ignoring-clustering">3.1 predictor selection using LASSO on the overall dataset (ignoring clustering)</h3>
<p>We will first apply LASSO to the overall dataset. The LASSO approach penalizes the likelihood function by introducing a parameter <code>lambda</code>. Optimal values for this parameter are then first determined via cross-validation, after which the penalized likelihood is optimized. Here, we will use 10-fold cross-validation to determine <code>lambda</code>, which can be specified using the argument <code>nfolds=10</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set random seed</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># determine penalization</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>lasso.fit <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> <span class="fu">as.matrix</span>(<span class="fu">subset</span>(ipd,<span class="at">select=</span>explanatory)), </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">y =</span> <span class="fu">as.matrix</span>(<span class="fu">subset</span>(ipd,<span class="at">select=</span><span class="fu">c</span>(dvt))),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">family=</span><span class="st">"binomial"</span>, <span class="at">type.measure=</span><span class="st">"mse"</span>, <span class="at">alpha=</span><span class="dv">1</span>, <span class="at">nfolds=</span><span class="dv">10</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># print coefficients</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso.fit, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>16 x 1 sparse Matrix of class "dgCMatrix"
                       s1
(Intercept) -3.194317e+00
age         -2.396894e-05
par          .           
tend         6.137009e-02
leg          2.808745e-01
pit          .           
altdiagn    -9.740994e-01
histdvt      .           
malign       4.281384e-01
surg         9.433021e-02
calfdif3     5.129627e-01
vein         7.098922e-02
oachst       4.068533e-01
sex          2.945087e-01
notraum      2.022761e-01
ddimdich     2.156104e+00</code></pre>
</div>
</div>
<p>As you can see, the variables <code>par</code>, <code>pit</code> and <code>histdvt</code> are omitted from the model.</p>
</section>
</section>
<section id="predictor-selection-using-lasso-with-mixed-effects" class="level2">
<h2 class="anchored" data-anchor-id="predictor-selection-using-lasso-with-mixed-effects">3.2 predictor selection using LASSO with mixed effects</h2>
<p>We may also adopt a variable selection approach for generalized linear mixed models by L1-penalized estimation <span class="citation" data-cites="groll_variable_2014">(<a href="#ref-groll_variable_2014" role="doc-biblioref">Groll and Tutz 2014</a>)</span>. This approach is related to LASSO, but tailored to multilevel data. We here assume random effects for the intercept term and the predictors <code>par</code>, <code>tend</code>, <code>leg</code>, <code>calfdif3</code>, <code>notraum</code> and <code>ddimdich</code>, in order to allow investigation of between-study heterogeneity in the corresponding regression coefficients. It may, however, be more appropriate to also assume random effects for the remaining predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmLasso)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>fmla <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"dvt ~"</span>, <span class="fu">paste</span>(explanatory, <span class="at">collapse=</span><span class="st">"+"</span>)))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>ipd<span class="sc">$</span>study <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(ipd<span class="sc">$</span>studyname)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Lets try 2 different penalties here.</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The optimal penalty can be identified through cross-validation</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">glmmLasso</span>(fmla, <span class="at">rnd =</span> <span class="fu">list</span>(<span class="at">study=</span><span class="sc">~</span><span class="dv">1</span><span class="sc">+</span>par<span class="sc">+</span>tend<span class="sc">+</span>leg<span class="sc">+</span>calfdif3<span class="sc">+</span>notraum<span class="sc">+</span>ddimdich), </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lambda=</span><span class="dv">10</span>, <span class="at">data =</span> ipd, <span class="at">family=</span><span class="fu">binomial</span>())</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">glmmLasso</span>(fmla, <span class="at">rnd =</span> <span class="fu">list</span>(<span class="at">study=</span><span class="sc">~</span><span class="dv">1</span><span class="sc">+</span>par<span class="sc">+</span>tend<span class="sc">+</span>leg<span class="sc">+</span>calfdif3<span class="sc">+</span>notraum<span class="sc">+</span>ddimdich), </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lambda=</span><span class="dv">100</span>, <span class="at">data =</span> ipd, <span class="at">family=</span><span class="fu">binomial</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that in the current LASSO approach, we have pre-specified values for <code>lambda</code> rather than estimating appropriate values via cross-validation. The main reason is that cross-validation has not properly been implemented yet for <code>glmmLasso()</code>. Hence, we can manually compare 2 prediction models <code>lm1</code> (where <code>lambda=10</code>) and <code>lm2</code> (where <code>lambda=100</code>) where we varied the amount of penalization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">lm1=</span><span class="fu">coef</span>(lm1), <span class="at">lm2=</span><span class="fu">coef</span>(lm2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    lm1          lm2
(Intercept) -3.68244903 -2.553318804
age          0.00000000  0.000000000
par          0.03783344  0.000000000
tend         0.19256115  0.029560532
leg          0.37849178  0.138545954
pit          0.05655308  0.031985192
altdiagn    -1.16471985 -0.927308252
histdvt      0.43592572  0.079241354
malign       0.46290621  0.301463496
surg         0.30508937  0.048349926
calfdif3     0.54041791  0.350388731
vein         0.27059765  0.080852868
oachst       0.76375526  0.279743415
sex          0.49574091  0.241923178
notraum      0.35659293  0.006034108
ddimdich     2.19902753  1.704898679</code></pre>
</div>
</div>
<p>Note that now the predictors <code>age</code> and, for the second model, <code>par</code> are omitted.</p>
<p><strong>Question 4.</strong> What could be potential reasons for predictors to not be included in the model?</p>
<p><em>Answer: Potential reasons for predictor not to be included in the model in every dataset include differences in case-mix (and predictor-effects) across studies or low variability of predictors or different reference standards to determine DVT.</em></p>
<p>From here onwards, we will stick to the predictors from the Oudega model (predictors <code>malign</code>, <code>surg</code>, <code>calfdif3</code>, <code>vein</code>, <code>oachst</code>, <code>sex</code>, <code>notraum</code>, <code>ddimdich</code>), but feel free to adjust the predictors according to information from the LASSO approach or other strategies. (<em>NOTE: it will actually be nice if some of you select different predictors to allow comparison of your model with fellow students</em>)</p>
<p>Define a new dataset including the outcome, study identifiers, and final predictors</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>xs.final <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"malign"</span>,<span class="st">"surg"</span>,<span class="st">"calfdif3"</span>,<span class="st">"vein"</span>,<span class="st">"oachst"</span>,<span class="st">"sex"</span>,<span class="st">"notraum"</span>,<span class="st">"ddimdich"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ipd2 <span class="ot">&lt;-</span> ipd[,<span class="fu">c</span>(<span class="st">"dvt"</span>,<span class="st">"studyid"</span>,<span class="st">"studyname"</span>,xs.final)]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ipd2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     dvt studyid studyname malign surg calfdif3 vein oachst sex notraum ddimdich
6901   1       1     amuse      0    0        1    0      0   1       1        0
6902   0       1     amuse      0    0        1    0      0   1       1        0
6903   0       1     amuse      0    0        0    1      0   1       0        0
6904   0       1     amuse      0    1        0    0      0   1       1        0
6905   0       1     amuse      0    0        0    1      0   1       0        0
6906   0       1     amuse      0    0        0    1      0   0       0        0</code></pre>
</div>
</div>
</section>
</section>
<section id="chapter-4" class="level1">
<h1>Chapter 4</h1>
<section id="internal-external-cross-validation-iecv" class="level2">
<h2 class="anchored" data-anchor-id="internal-external-cross-validation-iecv">Internal-external cross-validation (IECV)</h2>
<p>Now, we repeat the above but now we will develop the model using a so-called internal-external cross-validation (IECV), in which we develop the model on <code>n-1</code> studies, and validate the model in the remaining study. The procedure is described in full by <span class="citation" data-cites="debray_framework_2013">Thomas P. A. Debray et al. (<a href="#ref-debray_framework_2013" role="doc-biblioref">2013</a>)</span>.</p>
<p>We first introduce lists/variables to store model performance data in the validation populations. Performance data include the c-statistic (<code>cstat</code>), the calibration-in-the-large (<code>citl</code>), the calibration slope (<code>calslope</code>), as well as information on the total number of observed events (<code>O</code>), the total number of expected events (<code>E</code>), and the total sample size (<code>N</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>model.perf.val <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">validation.study=</span><span class="fu">unique</span>(ipd2<span class="sc">$</span>studyname), </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">cstat.lb=</span><span class="cn">NA</span>, <span class="at">cstat=</span><span class="cn">NA</span>, <span class="at">cstat.ub=</span><span class="cn">NA</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">citl=</span><span class="cn">NA</span>, <span class="at">citl.se=</span><span class="cn">NA</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">calslope=</span><span class="cn">NA</span>, <span class="at">calslope.se=</span><span class="cn">NA</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">O=</span><span class="cn">NA</span>, <span class="at">E=</span><span class="cn">NA</span>, <span class="at">N=</span><span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Question 5.</strong> Explain what aforementioned performance measures mean. How would you interpret the c-statistic, calibration-in-the-large, and the calibration slope?</p>
<p><em>Answer: c-statistic indicates the discriminative performance of the model at validation and is a measure for how well the prediction model is able to distinguish between individuals with and without the outcome. In determining the c-statistic, random pairs of individuals with and without the outcome are drawn. If the model performs well, it should assign a higher risk of the outcome to the individuals with the outcome than the ones without the outcome. The c-statistic then indicates the percentage of random pairs in which the model was able to correctly assign the higher risk to the individual with the outcome.</em></p>
<p><em>Answer: Calibration refers to the agreement between predicted risks and observed proportions and can be assessed in terms of baseline risk (intercept, or calibration-in-the-large) and the average strength of the predictor effects (calibration slope). The calibration slope at external validation reflects the combined effect of two issues: overfitting on the development data and true differences (between the development and validation set) in effects of predictors. Ideally the calibration should be 1. The more it deviates from 1, the worse thecalibration. The calibration slope is obtained by fitting a regression model with the linear predictor as calculated from the original model as a covariate.</em></p>
<p><em>Answer: Calibration-in-the-large indicates the difference between the mean predicted outcomes and the mean of the observed outcomes. Ideally, calibration-in-the-large should be zero. The more it deviates from zero, the worse the calibration is. The calibration-in-the-large is obtained by fitting a regression model with the linear predictor as calculated from the original model as an offset.</em></p>
<p>Run a IECV procedure. During this procedure we will create a PDF of the calibration plots (all are plotted in one PDF file)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">pdf</span>(<span class="st">"calibration_dvt_stacked.pdf"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nstudies){</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># define development and validation datasets</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  ipd.dev <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd2,ipd2<span class="sc">$</span>studyid<span class="sc">!=</span>i,<span class="at">select=</span><span class="sc">-</span><span class="fu">c</span>(studyid,studyname))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  ipd.val <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd2,ipd2<span class="sc">$</span>studyid<span class="sc">==</span>i,<span class="at">select=</span><span class="sc">-</span><span class="fu">c</span>(studyid,studyname))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># fit model in development data</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  fit.dev <span class="ot">&lt;-</span> <span class="fu">lrm</span>(dvt <span class="sc">~</span> ., <span class="at">data =</span> ipd.dev)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  predy.val <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit.dev, <span class="at">type=</span><span class="st">"fitted"</span>, <span class="at">newdata=</span>ipd.val)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  predlp.val <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit.dev, <span class="at">type=</span><span class="st">"lp"</span>, <span class="at">newdata=</span>ipd.val)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine calibration slope in validation data</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  fit.val.slope <span class="ot">&lt;-</span> <span class="fu">glm</span>(dvt <span class="sc">~</span> predlp.val, <span class="at">data=</span>ipd.val, <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine calibration-in-the-large in validation data</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  fit.val.citl <span class="ot">&lt;-</span> <span class="fu">glm</span>(dvt <span class="sc">~</span> <span class="dv">1</span>, <span class="at">offset=</span>predlp.val, <span class="at">data=</span>ipd.val, <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine discriminative performance (c statistic) in development and validation sets</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>  cstat.val <span class="ot">&lt;-</span> <span class="fu">roc</span>(ipd.val<span class="sc">$</span>dvt, predy.val,<span class="at">ci=</span>T)<span class="sc">$</span>ci[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine calibration in development set (plots + intercept / slope)</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">val.prob</span>(predy.val, ipd.val<span class="sc">$</span>dvt,<span class="at">g=</span><span class="dv">10</span>,</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="fu">paste</span>(<span class="st">"Predicted Probabiliy Validation, in study ="</span>,<span class="fu">paste</span>(i)),</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab =</span> <span class="fu">paste</span>(<span class="st">"Actual Probabiliy Validation, in study ="</span>,<span class="fu">paste</span>(i)))</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>validation.study[i] <span class="ot">&lt;-</span> (ipd<span class="sc">$</span>studyname[<span class="fu">which</span>(ipd<span class="sc">$</span>studyid<span class="sc">==</span>i)])[<span class="dv">1</span>]</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>cstat.lb[i] <span class="ot">&lt;-</span> cstat.val[<span class="dv">1</span>]</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>cstat[i] <span class="ot">&lt;-</span> cstat.val[<span class="dv">2</span>]</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>cstat.ub[i] <span class="ot">&lt;-</span> cstat.val[<span class="dv">3</span>]</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>citl[i] <span class="ot">&lt;-</span> fit.val.citl<span class="sc">$</span>coef[<span class="dv">1</span>]</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>citl.se[i] <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcov</span>(fit.val.citl)))[<span class="dv">1</span>]</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>calslope[i] <span class="ot">&lt;-</span> fit.val.slope<span class="sc">$</span>coef[<span class="dv">2</span>]</span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>calslope.se[i] <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcov</span>(fit.val.slope)))[<span class="dv">2</span>]</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>O[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(ipd.val<span class="sc">$</span>dvt)</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>E[i] <span class="ot">&lt;-</span><span class="fu">sum</span>(predy.val)</span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>N[i] <span class="ot">&lt;-</span> <span class="fu">dim</span>(ipd.val)[<span class="dv">1</span>]</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>() <span class="co"># this statement terminates the PDF statement</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-6.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-7.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-8.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-16-9.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Question 6.</strong> Inspect the calibration plots. Do you observe any peculiarities (e.g.&nbsp;mis-calibration)? Are these peculiarities a common phenomenon or do they only occur in specific data sets?</p>
<p><em>Answer: Calibration seems to be best in studies 6 and 7, but does show varying levels of mis-calibration in the other studies, with the model arguably showing the worst performance in study 5. In this study, consistent overprediction is present.</em></p>
<p>Recently, internal-external cross-validation has been implemented in the <code>metapred</code> function of the R package metamisc. Briefly, this approach will fit a pre-specified model separately in each study of the development sample, and pool the corresponding regression coefficients using random effects meta-analysis. The resulting model is then validated in the hold-out sample. This process is repeated, such that each study is used as hold-out sample once (<span class="citation" data-cites="de_jong_developing_2021">de Jong et al. (<a href="#ref-de_jong_developing_2021" role="doc-biblioref">2021</a>)</span>). Because the two-stage meta-analysis approach is more prone to estimation problems due to restricted sample size, we will use all variables except for <code>vein</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metamisc)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> dvt <span class="sc">~</span> malign <span class="sc">+</span> surg <span class="sc">+</span> calfdif3 <span class="sc">+</span> oachst <span class="sc">+</span> sex <span class="sc">+</span> notraum <span class="sc">+</span> ddimdich</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>fit.iecv <span class="ot">&lt;-</span> <span class="fu">metapred</span>(<span class="at">data=</span>ipd2, <span class="at">strata=</span><span class="st">"studyname"</span>, <span class="at">formula=</span>f, <span class="at">scope=</span>f, <span class="at">family=</span>binomial)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>fit.iecv </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: metapred(data = ipd2, strata = "studyname", formula = f, scope = f, 
    family = binomial)

Started with model:
dvt ~ malign + surg + calfdif3 + oachst + sex + notraum + ddimdich

Generalizability:
  unchanged
1 0.1252423

Cross-validation stopped after 0 steps, as no changes were requested. Final model:
Meta-analytic model of prediction models estimated in 9 strata. Coefficients: 
(Intercept)      malign        surg    calfdif3      oachst         sex     notraum    ddimdich 
 -4.5081436   0.5213894   0.3786508   1.0666247   0.6300266   0.4965409   0.6010044   2.7726126 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(fit.iecv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="chapter-5" class="level1">
<h1>Chapter 5</h1>
<section id="synthesis-of-performance-results" class="level2">
<h2 class="anchored" data-anchor-id="synthesis-of-performance-results">Synthesis of performance results</h2>
<p>Evaluate the results of the previous section.</p>
<section id="visual-assessment" class="level3">
<h3 class="anchored" data-anchor-id="visual-assessment">5.1 Visual assessment</h3>
<p><strong>Question 7.</strong> Summarize the performance of your model. What is the “average” concordance statistic, calibration slope and calibration-in-the-large statistic upon external validation? How would you interpret these “average” results?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(model.perf.val, <span class="dv">2</span>, <span class="at">FUN =</span> median)[<span class="fu">c</span>(<span class="st">"cstat"</span>,<span class="st">"citl"</span>,<span class="st">"calslope"</span>)] </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       cstat         citl     calslope 
 "0.8361078" " 0.2633315"  "0.9845390" </code></pre>
</div>
</div>
<p>We can obtain more appropriate summary estimates by applying random effects meta-analysis. To this purpose, we will use the <code>metafor</code> and <code>metamisc</code> packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metamisc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you may have noticed, evaluating the various calibration plots is not very straightforward. It may therefore be more helpful to extract the relevant performance statistics and construct so-called forest plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>metafor<span class="sc">::</span><span class="fu">forest</span>(<span class="at">x =</span> model.perf.val<span class="sc">$</span>citl, <span class="at">sei =</span> model.perf.val<span class="sc">$</span>citl.se, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">refline =</span> <span class="dv">0</span>, <span class="at">xlab =</span> <span class="st">"Calibration-in-the-large"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>metafor<span class="sc">::</span><span class="fu">forest</span>(<span class="at">x =</span> model.perf.val<span class="sc">$</span>calslope, <span class="at">sei =</span> model.perf.val<span class="sc">$</span>calslope.se, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">refline =</span> <span class="dv">1</span>, <span class="at">xlab =</span> <span class="st">"Calibration Slope"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>metafor<span class="sc">::</span><span class="fu">forest</span>(<span class="at">x =</span> model.perf.val<span class="sc">$</span>cstat, <span class="at">ci.lb =</span> model.perf.val<span class="sc">$</span>cstat.lb, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">ci.ub =</span> model.perf.val<span class="sc">$</span>cstat.ub, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">refline =</span> <span class="cn">NA</span>, <span class="at">xlab =</span> <span class="st">"Area under the ROC curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-20-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Question 8.</strong> Inspect the presence of between-study heterogeneity in model discrimination. Does the C-statsitic substantially vary across studies? What might be potential reasons for this?</p>
<p><em>Answer: The c-statistic was highest in study 3, and lowest in study 5. There seem to be substantial differences in c-statistics across studies. Potential reasons for this heterogeneity could be differences in study populations (case mix). Differences in predictor-outcome associations are less likely because the calibration slope is actually fairly consistent across studies.</em></p>
<p><strong>Question 9.</strong> Inspect the presence of heterogeneity in calibration performance. Does the calibration-in-the-large and calibration slope substantially vary across studies? What might be potential reasons for this?</p>
<p><em>Answer: As was expected from the median calibration we saw in Q7 the calibration slope was fairly homogeneous across studies, although studies 3 and 4 did deviate somewhat from 1. Potential reasons for this heterogeneity could be differences in study populations (case mix) or differences in predictor-outcome associations. In general, predictor-outcome associations are homogeneous across studies. More heterogeneity was observed in the calibration-in-the-large, with only one study (3) have 0 in the 95%CI. Calibration-in-the-large deviated most from 0 for studies 5 (CITL=-0.94) and 8 (CITL=0.94). Potential reasons for this heterogeneity could be the heterogeneity in prevalence of DVT.</em></p>
<p>Another way of looking at the calibration performance is to compare the total number of observed (<code>O</code>) with total number of predicted (<code>E</code>) events in each validation. The total O:E ratio provides a rough indication of the overall model calibration, and is strongly related to the calibration-in-the-large statistic (but may be easier to interpret). We can calculate the total O:E ratio for each validation study as follows. Note that we apply a log transformation to facilitate meta-analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the log O:E ratio and its standard error</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>oe.ad <span class="ot">&lt;-</span> <span class="fu">oecalc</span>(<span class="at">O=</span>O, <span class="at">E=</span>E, <span class="at">N=</span>N, <span class="at">data=</span>model.perf.val, <span class="at">g=</span><span class="st">"log(OE)"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>model.perf.val<span class="sc">$</span>logOE <span class="ot">&lt;-</span> oe.ad<span class="sc">$</span>theta</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>model.perf.val<span class="sc">$</span>logOE.se <span class="ot">&lt;-</span> oe.ad<span class="sc">$</span>theta.se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then generate a forest plot for the O:E ratio:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>metafor<span class="sc">::</span><span class="fu">forest</span>(<span class="at">x =</span> model.perf.val<span class="sc">$</span>logOE, <span class="at">sei =</span> model.perf.val<span class="sc">$</span>logOE.se, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">atrans =</span> exp, <span class="at">xlab =</span> <span class="st">"Total O:E ratio"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="meta-analysis-of-model-performance" class="level2">
<h2 class="anchored" data-anchor-id="meta-analysis-of-model-performance">5.2 Meta-analysis of model performance</h2>
<p>Here we will verify your answers to previous questions by performing meta-analysis of prediction model performance. A step-by-step guide on how to do this is presented by <span class="citation" data-cites="debray_guide_2017">T. P. A. Debray et al. (<a href="#ref-debray_guide_2017" role="doc-biblioref">2017</a>)</span>.</p>
<section id="calibration-in-the-large" class="level3">
<h3 class="anchored" data-anchor-id="calibration-in-the-large">5.2.1 Calibration-in-the-large</h3>
<p>Summarize the estimates of the calibration-in-the-large. To account for the potential presence of between-study heterogeneity we recommend a random effects meta-analysis. In line with previous recommendations, we propose to adopt restricted maximum likelihood estimation (<code>method="REML"</code>) and to use the Hartung-Knapp-Sidik-Jonkman method (<code>test = "knha"</code>) when calculating 95% confidence intervals for the average performance, to better account for the uncertainty in the estimated between-study heterogeneity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model.CITL <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> citl, <span class="at">sei =</span> citl.se, <span class="at">method =</span> <span class="st">"REML"</span>, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">test =</span> <span class="st">"knha"</span>, <span class="at">data =</span> model.perf.val)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.CITL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 9; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
 -7.1502   14.3005   18.3005   18.4593   20.7005   

tau^2 (estimated amount of total heterogeneity): 0.3339 (SE = 0.1750)
tau (square root of estimated tau^2 value):      0.5778
I^2 (total heterogeneity / total variability):   97.24%
H^2 (total variability / sampling variability):  36.17

Test for Heterogeneity:
Q(df = 8) = 251.2261, p-val &lt; .0001

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub    
  0.1048  0.1970  0.5317   8  0.6094  -0.3495  0.5591    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Question 10.</strong> What is the pooled estimate for the calibration-in-the-large? Provide the 95% confidence interval.</p>
<p><em>Answer: The summary estimate for the calibration-in-the-large is 0.1. The 95% CI ranges from -0.35 to 0.56.</em></p>
</section>
<section id="total-oe-ratio" class="level3">
<h3 class="anchored" data-anchor-id="total-oe-ratio">5.2.2 Total O:E ratio</h3>
<p>We can also calculate a summary estimate for the total O:E ratio. This ratio indicates whether, on average, our model tends to over-predict (O:E&lt;1) or under-predict (O:E&gt;1) the presence of DVT. Here, we will use the package <code>metamisc</code> to adopt the necessary transformations during meta-analysis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>model.OE <span class="ot">&lt;-</span> <span class="fu">with</span>(model.perf.val, <span class="fu">valmeta</span>(<span class="at">measure =</span> <span class="st">"OE"</span>, <span class="at">O =</span> O, <span class="at">E =</span> E, <span class="at">N =</span> N))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>model.OE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Summary Total O:E ratio with 95% confidence and (approximate) 95% prediction interval:

 Estimate       CIl       CIu       PIl       PIu 
1.0583246 0.7916031 1.4149149 0.4237079 2.6434509 

Number of studies included:  9</code></pre>
</div>
</div>
</section>
<section id="calibration-slope" class="level3">
<h3 class="anchored" data-anchor-id="calibration-slope">5.2.3 Calibration slope</h3>
<p>Summarize the estimates of the calibration slope. To account for the heterogeneity that is present we (as is generally recommended) perform a random effects meta-analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model.CS <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> calslope, <span class="at">sei =</span> calslope.se, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">test =</span> <span class="st">"knha"</span>, <span class="at">data =</span> model.perf.val)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.CS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 9; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
  6.5040  -13.0081   -9.0081   -8.8492   -6.6081   

tau^2 (estimated amount of total heterogeneity): 0.0021 (SE = 0.0053)
tau (square root of estimated tau^2 value):      0.0457
I^2 (total heterogeneity / total variability):   18.82%
H^2 (total variability / sampling variability):  1.23

Test for Heterogeneity:
Q(df = 8) = 9.0367, p-val = 0.3392

Model Results:

estimate      se     tval  df    pval   ci.lb   ci.ub      
  1.0399  0.0332  31.2744   8  &lt;.0001  0.9632  1.1165  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Question 11.</strong> What is the pooled estimate for the calibration slope? Provide the 95% confidence interval.</p>
<p><em>Answer: The summary estimate for the calibration slope is 1.04. The 95% CI ranges from 0.96 to 1.12.</em></p>
</section>
<section id="concordance-statistic" class="level3">
<h3 class="anchored" data-anchor-id="concordance-statistic">5.2.4 Concordance statistic</h3>
<p>We can use <code>metamisc</code> to perform a random effects meta-analysis of the concordance statistic. This package will apply a logit transformation as recommended by <span class="citation" data-cites="snell_meta-analysis_2018">Snell et al. (<a href="#ref-snell_meta-analysis_2018" role="doc-biblioref">2018</a>)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model.cstat <span class="ot">&lt;-</span> <span class="fu">valmeta</span>(<span class="at">cstat =</span> cstat, <span class="at">cstat.cilb =</span> cstat.lb, <span class="at">cstat.ciub =</span> cstat.ub, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> model.perf.val)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>model.cstat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Summary c-statistic with 95% confidence and (approximate) 95% prediction interval:

 Estimate       CIl       CIu       PIl       PIu 
0.8186195 0.7910871 0.8432425 0.7362892 0.8794546 

Number of studies included:  9</code></pre>
</div>
</div>
</section>
<section id="overview-of-performance-estiamtes" class="level3">
<h3 class="anchored" data-anchor-id="overview-of-performance-estiamtes">5.2.5 Overview of performance estiamtes</h3>
<p>An overview for all performance estimates, and their 95% prediction interval is given below:</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 36%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Performance statistic</th>
<th style="text-align: left;">Summary</th>
<th style="text-align: left;">lower CI</th>
<th style="text-align: left;">upper CI</th>
<th style="text-align: left;">lower PI</th>
<th style="text-align: left;">upper PI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Calibration-in-the-large</td>
<td style="text-align: left;">0.1</td>
<td style="text-align: left;">-0.35</td>
<td style="text-align: left;">0.56</td>
<td style="text-align: left;">-1.3</td>
<td style="text-align: left;">1.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total O:E ratio</td>
<td style="text-align: left;">1.06</td>
<td style="text-align: left;">0.79</td>
<td style="text-align: left;">1.41</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">2.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calibration slope</td>
<td style="text-align: left;">1.04</td>
<td style="text-align: left;">0.96</td>
<td style="text-align: left;">1.12</td>
<td style="text-align: left;">0.91</td>
<td style="text-align: left;">1.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Concordance statistic</td>
<td style="text-align: left;">0.82</td>
<td style="text-align: left;">0.79</td>
<td style="text-align: left;">0.84</td>
<td style="text-align: left;">0.74</td>
<td style="text-align: left;">0.88</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Question 12.</strong> Determine whether your model would be sufficiently adequate for use in routine care. Would you recommend any tailoring before implementation?</p>
<p><em>Answer: Discriminative performance seems to be good, as well as the calibration slope. Calibration-in-the-large seems suboptimal, so tailoring of the model could include accounting for heterogeneity in baseline risk, e.g.&nbsp;by using stratified intercepts or adding predictors. Alternative options would be to remove heterogeneous predictors from the model, or to add predictors that may explain this heterogeneity.</em></p>
</section>
</section>
</section>
<section id="chapter-6" class="level1">
<h1>Chapter 6</h1>
<section id="meta-regression" class="level2">
<h2 class="anchored" data-anchor-id="meta-regression">Meta-regression</h2>
<p>We will now assess different sources of between-study heterogeneity using meta-regression we specifically focus on whether care setting (primary / secondary), and mean age can explain some of the between-study heterogeneity.</p>
<p>First, add study related characteristics to the <code>model.perf.val</code> matrix</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define study level characteristics of interest</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>model.perf.val<span class="sc">$</span>care <span class="ot">&lt;-</span> model.perf.val<span class="sc">$</span>age.m <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># determine the care, country or mean age per study</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nstudies) { </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>care[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(ipd<span class="sc">$</span>care[ipd<span class="sc">$</span>studyname<span class="sc">==</span>model.perf.val<span class="sc">$</span>validation.study[i]])</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  model.perf.val<span class="sc">$</span>age.m[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(ipd<span class="sc">$</span>age[ipd<span class="sc">$</span>studyname<span class="sc">==</span>model.perf.val<span class="sc">$</span>validation.study[i]])</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now assess the influence of these characteristics on the model performance measures.</p>
</section>
<section id="calibration-in-the-large-1" class="level2">
<h2 class="anchored" data-anchor-id="calibration-in-the-large-1">6.1 Calibration-in-the-large</h2>
<p>We will perform a random effects meta-regression for level of care and mean age.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rma</span>(<span class="at">yi =</span> citl, <span class="at">sei =</span> citl.se, <span class="at">mods =</span> care, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">test =</span> <span class="st">"knha"</span>, <span class="at">data =</span> model.perf.val) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 9; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.0623 (SE = 0.0408)
tau (square root of estimated tau^2 value):             0.2495
I^2 (residual heterogeneity / unaccounted variability): 86.11%
H^2 (unaccounted variability / sampling variability):   7.20
R^2 (amount of heterogeneity accounted for):            81.35%

Test for Residual Heterogeneity:
QE(df = 7) = 41.9618, p-val &lt; .0001

Test of Moderators (coefficient 2):
F(df1 = 1, df2 = 7) = 29.0781, p-val = 0.0010

Model Results:

         estimate      se     tval  df    pval    ci.lb    ci.ub     
intrcpt    0.4519  0.1152   3.9220   7  0.0057   0.1794   0.7244  ** 
mods      -1.0380  0.1925  -5.3924   7  0.0010  -1.4932  -0.5829  ** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rma</span>(<span class="at">yi =</span> citl, <span class="at">sei =</span> citl.se, <span class="at">mods =</span> age.m, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">test =</span> <span class="st">"knha"</span>, <span class="at">data =</span> model.perf.val) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 9; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.3230 (SE = 0.1796)
tau (square root of estimated tau^2 value):             0.5684
I^2 (residual heterogeneity / unaccounted variability): 97.16%
H^2 (unaccounted variability / sampling variability):   35.17
R^2 (amount of heterogeneity accounted for):            3.25%

Test for Residual Heterogeneity:
QE(df = 7) = 243.2923, p-val &lt; .0001

Test of Moderators (coefficient 2):
F(df1 = 1, df2 = 7) = 1.2423, p-val = 0.3018

Model Results:

         estimate      se     tval  df    pval    ci.lb    ci.ub    
intrcpt    5.3559  4.7155   1.1358   7  0.2934  -5.7945  16.5064    
mods      -0.0905  0.0812  -1.1146   7  0.3018  -0.2823   0.1014    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="calibration-slope-1" class="level2">
<h2 class="anchored" data-anchor-id="calibration-slope-1">6.2 Calibration slope</h2>
<p>Perform a random effects meta-regression for the calibration slope.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rma</span>(<span class="at">yi =</span> calslope, <span class="at">sei =</span> calslope.se, <span class="at">mods =</span> care, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">test =</span> <span class="st">"knha"</span>, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> model.perf.val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 9; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.0019 (SE = 0.0057)
tau (square root of estimated tau^2 value):             0.0438
I^2 (residual heterogeneity / unaccounted variability): 17.23%
H^2 (unaccounted variability / sampling variability):   1.21
R^2 (amount of heterogeneity accounted for):            8.25%

Test for Residual Heterogeneity:
QE(df = 7) = 7.6442, p-val = 0.3650

Test of Moderators (coefficient 2):
F(df1 = 1, df2 = 7) = 1.2436, p-val = 0.3016

Model Results:

         estimate      se     tval  df    pval    ci.lb   ci.ub      
intrcpt    1.0653  0.0398  26.7552   7  &lt;.0001   0.9711  1.1594  *** 
mods      -0.0780  0.0700  -1.1152   7  0.3016  -0.2434  0.0874      

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rma</span>(<span class="at">yi =</span> calslope, <span class="at">sei =</span> calslope.se, <span class="at">mods =</span> age.m, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">test =</span> <span class="st">"knha"</span>, </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> model.perf.val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 9; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.0005 (SE = 0.0049)
tau (square root of estimated tau^2 value):             0.0229
I^2 (residual heterogeneity / unaccounted variability): 5.39%
H^2 (unaccounted variability / sampling variability):   1.06
R^2 (amount of heterogeneity accounted for):            75.02%

Test for Residual Heterogeneity:
QE(df = 7) = 8.0147, p-val = 0.3313

Test of Moderators (coefficient 2):
F(df1 = 1, df2 = 7) = 0.7377, p-val = 0.4188

Model Results:

         estimate      se    tval  df    pval    ci.lb   ci.ub    
intrcpt    0.1060  1.0898  0.0973   7  0.9252  -2.4710  2.6831    
mods       0.0160  0.0186  0.8589   7  0.4188  -0.0280  0.0599    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="R-prediction-ipdma---practical_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Question 13.</strong> Which characteristics seem to affect which performance measures?</p>
<p><em>Answer: Heterogeneity in the c-statistic seems to be somewhat explained by care, but not by mean age. Heterogeneity in calibration-in-the-large is explained by care, but not by mean age. Heterogeneity in the calibration slope is not explained by care nor mean age.</em></p>
<p><strong>Question 14.</strong> Following the previous question. For which populations would tailoring be necessary and how extensive should tailoring be? (intercept only, or also slope? Or even more adjustments needed?)</p>
<p><em>Answer: Based on the results, care seemed to have a substantial influence on the calibration-in-the-large. Thus, one way to account for this would be to e.g.&nbsp;incorporate a stratified intercept based the care-level of the studies, or include care as a covariate.</em></p>
<p><strong>Question 15.</strong> If deemed necessary (and if time allows), use the findings from previous questions to refine your model (e.g.&nbsp;by adding or omitting predictors, or by considering more complex associations) and repeat the IECV approach. Do you obtain more favorable results?</p>
</section>
</section>
<section id="chapter-7" class="level1">
<h1>Chapter 7</h1>
<section id="accounting-for-level-of-care" class="level2">
<h2 class="anchored" data-anchor-id="accounting-for-level-of-care">Accounting for level of care</h2>
<p>In the previous chapter, we identified level of care (<code>care</code>) as a major source of between-study heterogeity for the calibration-in-the-large of our model. Hence, we will include this predictor in our revised model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>ipd3 <span class="ot">&lt;-</span> ipd[,<span class="fu">c</span>(<span class="st">"dvt"</span>,<span class="st">"studyid"</span>,<span class="st">"studyname"</span>,<span class="st">"care"</span>,xs.final)]</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>model.perf.val2 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">array</span>(<span class="cn">NA</span>, <span class="at">dim=</span><span class="fu">c</span>(nstudies, <span class="dv">8</span>)))</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(model.perf.val2) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"validation.study"</span>, <span class="st">"cstat.lb"</span>, <span class="st">"cstat"</span>, <span class="st">"cstat.ub"</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"citl"</span>, <span class="st">"citl.se"</span>, <span class="st">"calslope"</span>, <span class="st">"calslope.se"</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nstudies){</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># define development and validation datasets</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  ipd.dev <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd3,ipd<span class="sc">$</span>studyid<span class="sc">!=</span>i,<span class="at">select=</span><span class="sc">-</span><span class="fu">c</span>(studyid,studyname))</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  ipd.val <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd3,ipd<span class="sc">$</span>studyid<span class="sc">==</span>i,<span class="at">select=</span><span class="sc">-</span><span class="fu">c</span>(studyid,studyname))</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># fit model in development data</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>  fit.dev <span class="ot">&lt;-</span> <span class="fu">lrm</span>(dvt <span class="sc">~</span> ., <span class="at">data =</span> ipd.dev)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine calibration slope in validation data</span></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>  fit.val.slope <span class="ot">&lt;-</span> <span class="fu">glm</span>(dvt <span class="sc">~</span> <span class="fu">predict</span>(fit.dev,<span class="at">type=</span><span class="st">"lp"</span>,<span class="at">newdata=</span>ipd.val),</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> ipd.val, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine calibration-in-the-large in validation data</span></span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>  fit.val.citl <span class="ot">&lt;-</span> <span class="fu">glm</span>(dvt <span class="sc">~</span> <span class="dv">1</span>, <span class="at">offset=</span><span class="fu">predict</span>(fit.dev,<span class="at">type=</span><span class="st">"lp"</span>,<span class="at">newdata=</span>ipd.val),</span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> ipd.val, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determine discriminative performance (c statistic) in development and validation sets</span></span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a>  cstat.dev <span class="ot">&lt;-</span> <span class="fu">roc</span>(ipd.dev<span class="sc">$</span>dvt,<span class="fu">predict</span>(fit.dev,<span class="at">type=</span><span class="st">"fitted"</span>),<span class="at">ci=</span>T)<span class="sc">$</span>ci[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a>  cstat.val <span class="ot">&lt;-</span> <span class="fu">roc</span>(ipd.val<span class="sc">$</span>dvt,<span class="fu">predict</span>(fit.dev,<span class="at">type=</span><span class="st">"fitted"</span>,<span class="at">newdata=</span>ipd.val),<span class="at">ci=</span>T)<span class="sc">$</span>ci[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb45-24"><a href="#cb45-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-25"><a href="#cb45-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-26"><a href="#cb45-26" aria-hidden="true" tabindex="-1"></a>  model.perf.val2[i,] <span class="ot">&lt;-</span> <span class="fu">c</span>(i, cstat.val,</span>
<span id="cb45-27"><a href="#cb45-27" aria-hidden="true" tabindex="-1"></a>                          fit.val.citl<span class="sc">$</span>coef[<span class="dv">1</span>], <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcov</span>(fit.val.citl)))[<span class="dv">1</span>],</span>
<span id="cb45-28"><a href="#cb45-28" aria-hidden="true" tabindex="-1"></a>                          fit.val.slope<span class="sc">$</span>coef[<span class="dv">2</span>], <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcov</span>(fit.val.slope)))[<span class="dv">2</span>])</span>
<span id="cb45-29"><a href="#cb45-29" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="chapter-8" class="level1">
<h1>Chapter 8</h1>
<section id="comparison-of-models" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-models">Comparison of models</h2>
<p>Now that we have come up with a certain model specification (through variable selection) and investigated the validity of the corresponding model (via IECV), we can summarize its generalizability for comparison purposes. Hereto, we will determine the probability that our model will achieve a c-statistic of at least 0.7, a calibration-in-the-large between -0.5 and 0.5, and a calibration slope between 0.8 and 1.2 in new populations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>logit <span class="ot">&lt;-</span> <span class="cf">function</span>(x) { <span class="fu">log</span>(x<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>x))}</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>calcProbGoodPerf <span class="ot">&lt;-</span> <span class="cf">function</span>(model.perf.val, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">min.cstat =</span> <span class="fl">0.7</span>, </span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">limits.citl =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>), </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">limits.slope =</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="fl">1.2</span>)) </span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    model.perf.val<span class="sc">$</span>logitcstat <span class="ot">&lt;-</span> <span class="fu">logit</span>(model.perf.val<span class="sc">$</span>cstat)</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    difflogitc <span class="ot">&lt;-</span> <span class="fu">logit</span>(model.perf.val<span class="sc">$</span>cstat.ub)<span class="sc">-</span><span class="fu">logit</span>(model.perf.val<span class="sc">$</span>cstat.lb)</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    model.perf.val<span class="sc">$</span>logitcstat.se <span class="ot">&lt;-</span> <span class="fu">abs</span>(difflogitc)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>))</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>    wsvar <span class="ot">&lt;-</span> model.perf.val[,<span class="fu">c</span>(<span class="st">"citl.se"</span>, <span class="st">"calslope.se"</span>, <span class="st">"logitcstat.se"</span>)]<span class="sc">**</span><span class="dv">2</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Multivariate meta-analysis of calibration-in-the-large, calibration slope and c-statistic</span></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Ideally we should provide within-study covariance to argument S, but for sake of simplicity</span></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># we here assume that, within studies, all performance estimates are independent of each other.</span></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">mvmeta</span>(<span class="fu">cbind</span>(citl, calslope, logitcstat)<span class="sc">~</span><span class="dv">1</span>, <span class="at">S=</span>wsvar, <span class="at">data=</span>model.perf.val, </span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method=</span><span class="st">"reml"</span>)</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Simulate 100000 new studies</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>    Nsim <span class="ot">=</span> <span class="dv">1000000</span> </span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>    mvmeta.var <span class="ot">&lt;-</span> <span class="fu">vcov</span>(fit) <span class="co"># Error (co)variance of the meta-analysis summary estimates</span></span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define between-study heterogeneity matrix</span></span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a>    mvmeta.tausq <span class="ot">&lt;-</span> fit<span class="sc">$</span>Psi </span>
<span id="cb46-26"><a href="#cb46-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb46-27"><a href="#cb46-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define degrees of freedom</span></span>
<span id="cb46-28"><a href="#cb46-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Total DF is (#studies - 3) because we have a trivariate MA</span></span>
<span id="cb46-29"><a href="#cb46-29" aria-hidden="true" tabindex="-1"></a>    df <span class="ot">&lt;-</span> (fit<span class="sc">$</span>dim)[[<span class="st">"m"</span>]]<span class="sc">-</span><span class="dv">3</span> </span>
<span id="cb46-30"><a href="#cb46-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-31"><a href="#cb46-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># pooled estimates of citl, calibration slope and logit c-statistic</span></span>
<span id="cb46-32"><a href="#cb46-32" aria-hidden="true" tabindex="-1"></a>    M <span class="ot">=</span> <span class="fu">coefficients</span>(fit) </span>
<span id="cb46-33"><a href="#cb46-33" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb46-34"><a href="#cb46-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Total variance</span></span>
<span id="cb46-35"><a href="#cb46-35" aria-hidden="true" tabindex="-1"></a>    V <span class="ot">=</span> mvmeta.var <span class="sc">+</span> mvmeta.tausq </span>
<span id="cb46-36"><a href="#cb46-36" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb46-37"><a href="#cb46-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Simulate "true" performance estimates for new studies</span></span>
<span id="cb46-38"><a href="#cb46-38" aria-hidden="true" tabindex="-1"></a>    xrand <span class="ot">=</span> <span class="fu">rmt</span>(Nsim, <span class="at">mean=</span>M, <span class="at">S=</span>V, <span class="at">df=</span>df ) </span>
<span id="cb46-39"><a href="#cb46-39" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb46-40"><a href="#cb46-40" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Probability of "good" performance</span></span>
<span id="cb46-41"><a href="#cb46-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># cstat &gt; 0.7, citl between -0.5 to 0.5, slope between 0.8 and 1.2</span></span>
<span id="cb46-42"><a href="#cb46-42" aria-hidden="true" tabindex="-1"></a>    <span class="fu">length</span>(<span class="fu">which</span>(xrand[,<span class="dv">3</span>]<span class="sc">&gt;</span><span class="fu">logit</span>(min.cstat) <span class="sc">&amp;</span> </span>
<span id="cb46-43"><a href="#cb46-43" aria-hidden="true" tabindex="-1"></a>                   xrand[,<span class="dv">2</span>] <span class="sc">&gt;</span> limits.slope[<span class="dv">1</span>] <span class="sc">&amp;</span> </span>
<span id="cb46-44"><a href="#cb46-44" aria-hidden="true" tabindex="-1"></a>                   xrand[,<span class="dv">2</span>] <span class="sc">&lt;</span> limits.slope[<span class="dv">2</span>] <span class="sc">&amp;</span> </span>
<span id="cb46-45"><a href="#cb46-45" aria-hidden="true" tabindex="-1"></a>                   xrand[,<span class="dv">1</span>] <span class="sc">&gt;</span> limits.citl[<span class="dv">1</span>] <span class="sc">&amp;</span> </span>
<span id="cb46-46"><a href="#cb46-46" aria-hidden="true" tabindex="-1"></a>                   xrand[,<span class="dv">1</span>] <span class="sc">&lt;</span> limits.citl[<span class="dv">2</span>]))<span class="sc">/</span>Nsim</span>
<span id="cb46-47"><a href="#cb46-47" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb46-48"><a href="#cb46-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-49"><a href="#cb46-49" aria-hidden="true" tabindex="-1"></a><span class="fu">calcProbGoodPerf</span>(model.perf.val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.544925</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcProbGoodPerf</span>(model.perf.val2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.809115</code></pre>
</div>
</div>
</section>
</section>
<section id="chapter-9" class="level1">
<h1>Chapter 9</h1>
<section id="develop-final-model-to-be-reported" class="level2">
<h2 class="anchored" data-anchor-id="develop-final-model-to-be-reported">Develop final model to be reported</h2>
<p>Here we take the Oudega model with level of care as extra predictor because this model yielded the best chance of “good” external performance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>ipd.dev <span class="ot">&lt;-</span> <span class="fu">subset</span>(ipd3, <span class="at">select=</span><span class="sc">-</span><span class="fu">c</span>(studyid,studyname))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>fit.final <span class="ot">&lt;-</span> <span class="fu">glm</span>(dvt<span class="sc">~</span>., <span class="at">data =</span> ipd.dev, <span class="at">family=</span>binomial)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-de_jong_developing_2021" class="csl-entry" role="doc-biblioentry">
de Jong, Valentijn M. T., Karel G. M. Moons, Marinus J. C. Eijkemans, Richard D. Riley, and Thomas P. A. Debray. 2021. <span>“Developing More Generalizable Prediction Models from Pooled Studies and Large Clustered Data Sets.”</span> <em>Statistics in Medicine</em>. <a href="https://doi.org/10.1002/sim.8981">https://doi.org/10.1002/sim.8981</a>.
</div>
<div id="ref-debray_guide_2017" class="csl-entry" role="doc-biblioentry">
Debray, T. P. A., Johanna A A G Damen, Kym I. E. Snell, Joie Ensor, Lotty Hooft, Johannes B Reitsma, R D Riley, and K. G M Moons. 2017. <span>“A Guide to Systematic Review and Meta-Analysis of Prediction Model Performance.”</span> <em>BMJ</em> 356: i6460. <a href="https://doi.org/10.1136/bmj.i6460">https://doi.org/10.1136/bmj.i6460</a>.
</div>
<div id="ref-debray_framework_2013" class="csl-entry" role="doc-biblioentry">
Debray, Thomas P. A., Karel G. M. Moons, Ikhlaaq Ahmed, Hendrik Koffijberg, and Richard David Riley. 2013. <span>“A Framework for Developing, Implementing, and Evaluating Clinical Prediction Models in an Individual Participant Data Meta-Analysis.”</span> <em>Stat Med</em> 32 (18): 3158–80. <a href="https://doi.org/10.1002/sim.5732">https://doi.org/10.1002/sim.5732</a>.
</div>
<div id="ref-geersing_exclusion_2014" class="csl-entry" role="doc-biblioentry">
Geersing, G. J., N. P. A. Zuithoff, C. Kearon, D. R. Anderson, A. J. ten Cate-Hoek, J. L. Elf, S. M. Bates, et al. 2014. <span>“Exclusion of Deep Vein Thrombosis Using the <span>Wells</span> Rule in Clinically Important Subgroups: Individual Patient Data Meta-Analysis.”</span> <em>BMJ</em> 348 (March): g1340. <a href="https://doi.org/10.1136/bmj.g1340">https://doi.org/10.1136/bmj.g1340</a>.
</div>
<div id="ref-groll_variable_2014" class="csl-entry" role="doc-biblioentry">
Groll, Andreas, and Gerhard Tutz. 2014. <span>“Variable Selection for Generalized Linear Mixed Models by <span>L</span> 1-Penalized Estimation.”</span> <em>Statistics and Computing</em> 24 (2): 137–54. <a href="https://doi.org/10.1007/s11222-012-9359-z">https://doi.org/10.1007/s11222-012-9359-z</a>.
</div>
<div id="ref-snell_meta-analysis_2018" class="csl-entry" role="doc-biblioentry">
Snell, Kym I E, Joie Ensor, Thomas P A Debray, Karel G M Moons, and Richard D. Riley. 2018. <span>“Meta-Analysis of Prediction Model Performance Across Multiple Studies: <span>Which</span> Scale Helps Ensure Between-Study Normality for the <span>C</span>-Statistic and Calibration Measures?”</span> <em>Statistical Methods in Medical Research</em> 27 (11): 3505–22. <a href="https://doi.org/10.1177/0962280217705678">https://doi.org/10.1177/0962280217705678</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>